repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files
      - id: detect-private-key
      - id: double-quote-string-fixer
        args: ['--autofix']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0 # latest secure version before v9
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@7.32.0', 'eslint-config-react-app']
