name: CI testing

on:
  pull_request:

jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies (Web)
        run: cd web && npm install
      - name: Run tests (Web)
        run: cd web && npm test
  test-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies (Mobile)
        run: cd mobile && npm install
      - name: Run tests (Mobile)
        run: cd mobile && npm test
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies (Server)
        run: cd server && npm install
      - name: Run tests (Server)
        env:
          MONGO_UNAME: ${{ secrets.MONGO_UNAME }}
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
        run: cd server && npm test
