name: CI testing

on:
  push:
  pull_request:


jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies (Web)
        run: cd web && npm install
      - name: Run tests (Web)
        run: cd web && npm test
